#!/usr/bin/env bash

: "${INIT_LANG:=auto}"
INIT_LANG_MODE="${INIT_LANG_MODE:-${INIT_LANG}}"
INIT_EFFECTIVE_LANG="en"
INIT_LANG_WARNING=""

declare -Ag I18N_EN I18N_RU INIT_MODULE_DESCRIPTION_KEYS

i18n_detect_locale() { local l="${LC_ALL:-${LC_MESSAGES:-${LANG:-C}}}"; case "$l" in ru*|RU*) printf ru;; *) printf en;; esac; }
i18n_normalize_lang() { case "${1:-auto}" in en|ru|auto) printf '%s' "$1";; *) printf en; return 1;; esac; }
i18n_set_lang() { local mode="${1:-auto}"; INIT_LANG_WARNING=""; if ! i18n_normalize_lang "$mode" >/dev/null; then INIT_LANG_WARNING="Unsupported language '$mode'; using English"; mode=en; fi; INIT_LANG_MODE="$mode"; INIT_LANG="$mode"; if [ "$mode" = auto ]; then INIT_EFFECTIVE_LANG="$(i18n_detect_locale)"; else INIT_EFFECTIVE_LANG="$mode"; fi; }
i18n_get() { local key="$1"; if [ "${INIT_EFFECTIVE_LANG:-en}" = ru ] && [[ -v "I18N_RU[$key]" ]]; then printf '%s' "${I18N_RU[$key]}"; elif [[ -v "I18N_EN[$key]" ]]; then printf '%s' "${I18N_EN[$key]}"; else printf '%s' "$key"; fi; }
i18n_bool() { [ "${1:-0}" = 1 ] && i18n_get common.yes || i18n_get common.no; }
i18n_status() { local s="${1// /_}"; i18n_get "status.$s"; }
i18n_lang_name() { case "${1:-${INIT_EFFECTIVE_LANG:-en}}" in ru) i18n_get lang.russian;; auto) i18n_get lang.auto;; *) i18n_get lang.english;; esac; }
i18n_module_description() { local key="${INIT_MODULE_DESCRIPTION_KEYS[$1]:-}"; [ -n "$key" ] && i18n_get "$key" || printf '%s' "${INIT_MODULE_DESCRIPTIONS[$1]:-}"; }

I18N_EN=(
[app.title]='Init — VPS bootstrap tool' [screen.main]='Main menu' [screen.check]='Check server' [screen.plan]='Plan' [screen.apply]='Apply' [screen.modules]='Select modules' [screen.config]='Configuration' [screen.ports]='Firewall ports' [screen.effective_config]='Effective configuration' [screen.available_modules]='Available modules' [screen.help]='Help' [screen.save]='Save configuration' [screen.load]='Load configuration' [screen.language]='Language'
[main.section_actions]='CHECK AND APPLY' [main.section_config]='CONFIGURATION' [main.section_project]='PROJECT' [main.check]='Check server' [main.plan]='Show plan' [main.apply]='Apply configuration' [main.modules]='Select modules' [main.config]='Edit configuration' [main.effective_config]='Show current configuration' [main.available_modules]='Available modules' [main.help]='Help' [main.save]='Save configuration' [main.load]='Load configuration' [main.language]='Language' [main.exit]='Exit' [main.summary]='Summary' [main.target_user]='Target user' [main.selected_modules]='Selected modules' [main.configuration]='Configuration' [main.color_mode]='Color mode' [main.enabled]='enabled' [main.disabled]='disabled' [main.defaults]='defaults'
[common.choice]='Choice: ' [common.back]='Back' [common.cancel]='Cancel' [common.confirm]='Confirm' [common.yes]='Yes' [common.no]='No' [common.press_enter]='Press Enter to return to the menu...' [common.invalid_choice]='Invalid choice.' [common.ok]='OK' [common.error]='ERROR' [common.warning]='WARNING' [common.info]='INFO' [common.not_selected]='not selected' [common.empty]='empty'
[modules.select_all]='Select all' [modules.select_none]='Select none' [modules.defaults]='Defaults' [modules.cancelled]='Selection cancelled.' [modules.deps_added]='These dependencies were selected automatically:'
[config.git_name]='Git name' [config.git_email]='Git email' [config.ssh_key_path]='SSH key path' [config.ssh_key_comment]='SSH key comment' [config.allow_http]='Allow HTTP' [config.allow_https]='Allow HTTPS' [config.allow_port]='Additional allow-port' [config.upgrade]='Upgrade' [config.assume_yes]='Assume yes' [config.repair_permissions]='Repair permissions' [config.force_apply]='Force apply' [config.new_value]='New value (empty keep, * clear): ' [config.target_user_prompt]='Enter target user (empty keeps current). Type root only if you really want root.' [config.user]='User: ' [config.root_confirm]='Root selected. Continue? [y/N]: ' [config.root_not_selected]='Root not selected.'
[ports.title]='Additional firewall ports' [ports.add]='Add port' [ports.remove]='Remove port' [ports.clear]='Clear all' [ports.prompt]='Port (PORT/tcp or PORT/udp): ' [ports.remove_number]='Remove number: ' [ports.invalid]='Invalid or duplicate port.' [ports.invalid_number]='Invalid number.'
[results.module]='Module' [results.status]='Status' [results.details]='Details' [results.summary]='Summary' [results.configured]='Configured' [results.needs_changes]='Needs changes' [results.failed]='Failed' [results.blocked]='Blocked' [results.applied]='Applied' [results.unchanged]='Unchanged' [results.skipped]='Skipped'
[status.configured]='Configured' [status.needs_changes]='Needs changes' [status.planned]='Needs changes' [status.applied]='Applied' [status.unchanged]='Unchanged' [status.failed]='Failed' [status.blocked]='Blocked' [status.skipped]='Skipped' [status.check_failed]='Failed'
[plan.warning_firewall]='Warning: Firewall configuration may affect the current SSH session.' [plan.warning_docker]='Warning: Docker installation may change repositories and groups.' [plan.warning_packages]='Warning: System packages may be upgraded and services may restart.' [apply.selected_modules]='Selected modules' [apply.repair_warning]='Existing SSH file ownership or permissions may be changed.' [apply.confirm]='Apply these changes? [y/N]: ' [apply.cancelled]='Apply cancelled.' [apply.github_ssh_key]='GitHub SSH public key' [apply.github_ssh_key_hint]='Add this public key to GitHub as an account SSH key or a repository Deploy key. Never upload the private key.' [plan.apply]='Apply this plan' [plan.change_modules]='Change modules' [plan.change_config]='Change configuration'
[save.path]='Save path [./server.conf]: ' [save.exists]='File exists. Overwrite? [y/N]: ' [save.not_overwritten]='Not overwritten.' [save.no_newlines]='Values with newlines cannot be saved.' [save.saved]='Configuration saved to' [load.path]='Config path: ' [load.no_path]='No path entered.' [load.loaded]='Configuration loaded from' [load.failed]='Load failed; previous menu state restored.'
[lang.choose]='Choose language' [lang.english]='English' [lang.russian]='Русский' [lang.auto]='Auto — system locale' [lang.changed]='Language changed.'
[help.text]=$'Interactive help\n\nCheck compares selected modules with the current server and does not change the system.\nPlan prints the exact changes that selected modules would make without changing the system.\nApply shows a plan, asks for explicit confirmation, runs the existing apply engine, and post-checks results.\nModules are selected from the registry; dependencies are resolved automatically and run once.\nTarget user is used by user-scoped modules such as git and ssh_key. Root is never assumed silently.\nUse command mode for automation:\n\nMenu: Check server\nCLI:  ./init check\n\nMenu: Apply Docker\nCLI:  sudo ./init apply docker'
[module.system.description]='Validate supported Ubuntu/Debian platform prerequisites' [module.packages.description]='Install base apt packages' [module.docker.description]='Install Docker Engine and Compose plugin' [module.git.description]="Configure target user's global Git identity" [module.ssh_key.description]="Create/check target user's SSH key" [module.firewall.description]='Install and enable UFW rules' [module.security.description]='Install basic security packages'
)
I18N_RU=(
[app.title]='Init — настройка VPS' [screen.main]='Главное меню' [screen.check]='Проверка сервера' [screen.plan]='План изменений' [screen.apply]='Применение конфигурации' [screen.modules]='Выбор модулей' [screen.config]='Конфигурация' [screen.ports]='Порты firewall' [screen.effective_config]='Текущая конфигурация' [screen.available_modules]='Доступные модули' [screen.help]='Справка' [screen.save]='Сохранение конфигурации' [screen.load]='Загрузка конфигурации' [screen.language]='Язык'
[main.section_actions]='ПРОВЕРКА И ПРИМЕНЕНИЕ' [main.section_config]='НАСТРОЙКА' [main.section_project]='ПРОЕКТ' [main.check]='Проверить сервер' [main.plan]='Показать план' [main.apply]='Применить конфигурацию' [main.modules]='Выбрать модули' [main.config]='Изменить конфигурацию' [main.effective_config]='Показать текущую конфигурацию' [main.available_modules]='Доступные модули' [main.help]='Справка' [main.save]='Сохранить конфигурацию' [main.load]='Загрузить конфигурацию' [main.language]='Язык' [main.exit]='Выход' [main.summary]='Сводка' [main.target_user]='Пользователь' [main.selected_modules]='Выбрано модулей' [main.configuration]='Конфигурация' [main.color_mode]='Цвет' [main.enabled]='включён' [main.disabled]='выключен' [main.defaults]='по умолчанию'
[common.choice]='Выбор: ' [common.back]='Назад' [common.cancel]='Отмена' [common.confirm]='Подтвердить' [common.yes]='Да' [common.no]='Нет' [common.press_enter]='Нажмите Enter для возврата в меню...' [common.invalid_choice]='Неверный выбор.' [common.ok]='OK' [common.error]='ОШИБКА' [common.warning]='ВНИМАНИЕ' [common.info]='INFO' [common.not_selected]='не выбран' [common.empty]='пусто'
[results.module]='Модуль' [results.status]='Статус' [results.details]='Подробности' [results.summary]='Сводка' [results.configured]='Настроено' [results.needs_changes]='Требуются изменения' [results.failed]='Ошибки' [results.blocked]='Заблокировано' [results.applied]='Применено' [results.unchanged]='Без изменений' [results.skipped]='Пропущено' [status.configured]='Настроено' [status.needs_changes]='Требуются изменения' [status.planned]='Требуются изменения' [status.applied]='Применено' [status.unchanged]='Без изменений' [status.failed]='Ошибка' [status.blocked]='Заблокировано' [status.skipped]='Пропущено' [status.check_failed]='Ошибка'
[modules.select_all]='Выбрать все' [modules.select_none]='Снять выбор' [modules.defaults]='По умолчанию' [modules.cancelled]='Выбор отменён.' [modules.deps_added]='Эти зависимости выбраны автоматически:'
[config.git_name]='Имя Git' [config.git_email]='Email Git' [config.ssh_key_path]='Путь к SSH-ключу' [config.ssh_key_comment]='Комментарий SSH-ключа' [config.allow_http]='Разрешить HTTP' [config.allow_https]='Разрешить HTTPS' [config.allow_port]='Дополнительный порт' [config.upgrade]='Обновлять пакеты' [config.assume_yes]='Автоподтверждение' [config.repair_permissions]='Исправлять права' [config.force_apply]='Принудительное применение' [config.new_value]='Новое значение (пусто — оставить, * — очистить): ' [config.target_user_prompt]='Введите пользователя (пусто — оставить текущего). root выбирайте только осознанно.' [config.user]='Пользователь: ' [config.root_confirm]='Выбран root. Продолжить? [y/N]: ' [config.root_not_selected]='root не выбран.'
[ports.title]='Дополнительные порты firewall' [ports.add]='Добавить порт' [ports.remove]='Удалить порт' [ports.clear]='Очистить все' [ports.prompt]='Порт (PORT/tcp или PORT/udp): ' [ports.remove_number]='Номер для удаления: ' [ports.invalid]='Некорректный или повторяющийся порт.' [ports.invalid_number]='Некорректный номер.'
[plan.warning_firewall]='Внимание: настройка firewall может повлиять на текущую SSH-сессию.' [plan.warning_docker]='Внимание: установка Docker может изменить репозитории и группы пользователя.' [plan.warning_packages]='Внимание: системные пакеты могут быть обновлены, а службы перезапущены.' [apply.selected_modules]='Выбранные модули' [apply.repair_warning]='Права или владелец существующих SSH-файлов могут быть изменены.' [apply.confirm]='Применить эти изменения? [y/N]: ' [apply.cancelled]='Применение отменено.' [apply.github_ssh_key]='Публичный SSH-ключ для GitHub' [apply.github_ssh_key_hint]='Добавьте этот публичный ключ в GitHub как SSH-ключ аккаунта или Deploy key репозитория. Приватный ключ никогда не загружайте.' [plan.apply]='Применить этот план' [plan.change_modules]='Изменить модули' [plan.change_config]='Изменить конфигурацию'
[lang.choose]='Выберите язык' [lang.english]='English' [lang.russian]='Русский' [lang.auto]='Auto — системная локаль' [lang.changed]='Язык изменён.'
[module.system.description]='Проверка совместимости Ubuntu/Debian' [module.packages.description]='Установка базовых системных пакетов' [module.docker.description]='Установка Docker Engine и Compose' [module.git.description]='Настройка глобальной Git-конфигурации пользователя' [module.ssh_key.description]='Создание и проверка SSH-ключа пользователя' [module.firewall.description]='Настройка правил UFW' [module.security.description]='Установка базовых средств безопасности'
)
for _m in system packages docker git ssh_key firewall security; do INIT_MODULE_DESCRIPTION_KEYS[$_m]="module.$_m.description"; done
i18n_set_lang "${INIT_LANG_MODE:-${INIT_LANG:-auto}}"
