#!/usr/bin/env bash

MENU_INTERRUPTED=0
MENU_OLD_INT_ACTION=""
MENU_OLD_INT_HAD_TRAP=0
MENU_FLASH_TYPE=""
MENU_FLASH_TEXT=""
UI_LABEL_WIDTH=26
UI_MENU_LABEL_WIDTH=32
UI_WIDTH=72

ui_detect_width() { local c=72; if [ -t 1 ] && [ "${TERM:-}" != dumb ] && need_cmd tput; then c="$(tput cols 2>/dev/null || printf 72)"; fi; [[ "$c" =~ ^[0-9]+$ ]] || c=72; [ "$c" -lt 60 ] && c=60; [ "$c" -gt 100 ] && c=100; UI_WIDTH="$c"; }
ui_init_colors() { if [ "${OUTPUT_FORMAT:-text}" = json ] || [ ! -t 1 ] || [ -n "${NO_COLOR:-}" ] || [ "${INIT_NO_COLOR:-0}" = 1 ]; then UI_COLOR_TITLE=""; UI_COLOR_SECTION=""; UI_COLOR_NUMBER=""; UI_COLOR_VALUE=""; UI_COLOR_MUTED=""; UI_COLOR_SUCCESS=""; UI_COLOR_WARNING=""; UI_COLOR_ERROR=""; UI_COLOR_RESET=""; else UI_COLOR_TITLE="${COLOR_BOLD}${COLOR_BLUE}"; UI_COLOR_SECTION="${COLOR_BOLD}"; UI_COLOR_NUMBER="${COLOR_BLUE}"; UI_COLOR_VALUE=""; UI_COLOR_MUTED="${COLOR_GRAY}"; UI_COLOR_SUCCESS="${COLOR_GREEN}"; UI_COLOR_WARNING="${COLOR_YELLOW}"; UI_COLOR_ERROR="${COLOR_RED}"; UI_COLOR_RESET="${COLOR_RESET}"; fi; }
ui_char() { if [ "${INIT_ASCII_ONLY:-0}" = 1 ]; then case "$1" in tl|tr|bl|br) printf '+';; h) printf '-';; v) printf '|';; esac; else case "$1" in tl) printf '┌';; tr) printf '┐';; bl) printf '└';; br) printf '┘';; h) printf '─';; v) printf '│';; esac; fi; }
ui_repeat() { local ch="$1" n="$2" i; for ((i=0; i<n; i++)); do printf '%s' "$ch"; done; }
ui_title_text() { local t; t="$(i18n_get app.title)"; [ "${INIT_ASCII_ONLY:-0}" = 1 ] && t="${t//—/-}"; printf "%s" "$t"; }
ui_header() { ui_detect_width; ui_init_colors; local section="$1" h; h="$(ui_char h)"; printf '%s%s%s%s\n' "$(ui_char tl)" "$(ui_repeat "$h" $((UI_WIDTH-2)))" "$(ui_char tr)" ""; printf '%s %s%s%s\n' "$(ui_char v)" "${UI_COLOR_TITLE}" "$(ui_title_text)" "${UI_COLOR_RESET}"; printf '%s %s\n' "$(ui_char v)" "$section"; printf '%s%s%s\n\n' "$(ui_char bl)" "$(ui_repeat "$h" $((UI_WIDTH-2)))" "$(ui_char br)"; }
ui_screen() { menu_clear_screen; ui_header "$(i18n_get "screen.$1")"; menu_render_flash; }
ui_section() { printf '\n%s%s%s\n' "${UI_COLOR_SECTION}" "$1" "${UI_COLOR_RESET}"; }
ui_separator() { printf '%s\n' "$(ui_repeat '-' "$UI_WIDTH")"; }
ui_key_value() { printf '  %-*s %s%s%s\n' "$UI_LABEL_WIDTH" "$1" "${UI_COLOR_VALUE}" "$2" "${UI_COLOR_RESET}"; }
ui_menu_item() { printf '  %s%2s%s) %-*s %s\n' "${UI_COLOR_NUMBER}" "$1" "${UI_COLOR_RESET}" "$UI_MENU_LABEL_WIDTH" "$2" "${3:-}"; }
ui_hint() { printf '%s%s%s\n' "${UI_COLOR_MUTED}" "$1" "${UI_COLOR_RESET}"; }
ui_status() { local s="$1" t; t="$(i18n_status "$s")"; case "$s" in configured|applied|unchanged) printf '%s%s%s' "$UI_COLOR_SUCCESS" "$t" "$UI_COLOR_RESET";; failed|blocked|check_failed) printf '%s%s%s' "$UI_COLOR_ERROR" "$t" "$UI_COLOR_RESET";; *) printf '%s%s%s' "$UI_COLOR_WARNING" "$t" "$UI_COLOR_RESET";; esac; }

menu_on_int() { MENU_INTERRUPTED=1; printf '\nInterrupted.\n' >&2; }
menu_enter() { local old; old="$(trap -p INT || true)"; if [ -n "$old" ]; then MENU_OLD_INT_HAD_TRAP=1; MENU_OLD_INT_ACTION="${old#trap -- }"; MENU_OLD_INT_ACTION="${MENU_OLD_INT_ACTION% INT}"; MENU_OLD_INT_ACTION="${MENU_OLD_INT_ACTION#\'}"; MENU_OLD_INT_ACTION="${MENU_OLD_INT_ACTION%\'}"; else MENU_OLD_INT_HAD_TRAP=0; MENU_OLD_INT_ACTION=""; fi; trap menu_on_int INT; }
menu_leave() { if [ "$MENU_OLD_INT_HAD_TRAP" = 1 ]; then trap -- "$MENU_OLD_INT_ACTION" INT; else trap - INT; fi; }
menu_clear_screen() { [ "${INIT_NO_CLEAR:-0}" = 1 ] && return 0; [ -t 1 ] || return 0; need_cmd clear && clear; }
menu_pause() { printf '\n%s ' "$(i18n_get common.press_enter)"; IFS= read -r _ || return 0; }
menu_read() { local __var="$1" prompt="${2:-}"; MENU_INTERRUPTED=0; [ -n "$prompt" ] && printf '%s' "$prompt"; IFS= read -r "$__var" || return 1; [ "$MENU_INTERRUPTED" = 1 ] && return 130; return 0; }
menu_confirm() { local ans; menu_read ans "$1" || return 1; case "$ans" in y|Y|yes|YES|д|Д|да|ДА) return 0;; *) return 1;; esac; }
menu_join() { local IFS="$1"; shift; printf '%s' "$*"; }
menu_has() { local n="$1" x; shift; for x in "$@"; do [ "$x" = "$n" ] && return 0; done; return 1; }
menu_flash_success(){ MENU_FLASH_TYPE=success; MENU_FLASH_TEXT="$*"; }; menu_flash_warning(){ MENU_FLASH_TYPE=warning; MENU_FLASH_TEXT="$*"; }; menu_flash_error(){ MENU_FLASH_TYPE=error; MENU_FLASH_TEXT="$*"; }; menu_flash_info(){ MENU_FLASH_TYPE=info; MENU_FLASH_TEXT="$*"; }
menu_render_flash(){ [ -z "$MENU_FLASH_TEXT" ] && return 0; local label color; case "$MENU_FLASH_TYPE" in success) label=$(i18n_get common.ok); color=$UI_COLOR_SUCCESS;; warning) label=$(i18n_get common.warning); color=$UI_COLOR_WARNING;; error) label=$(i18n_get common.error); color=$UI_COLOR_ERROR;; *) label=$(i18n_get common.info); color=$UI_COLOR_MUTED;; esac; printf '%s%s:%s %s\n\n' "$color" "$label" "$UI_COLOR_RESET" "$MENU_FLASH_TEXT"; MENU_FLASH_TYPE=""; MENU_FLASH_TEXT=""; }
menu_invalid(){ menu_flash_error "$(i18n_get common.invalid_choice)"; }
menu_requested_or_default() { MENU_SELECTED=(); local m; if [ "${#REQUESTED_MODULES[@]}" -gt 0 ]; then MENU_SELECTED=("${REQUESTED_MODULES[@]}"); else for m in "${INIT_REGISTERED_MODULES[@]}"; do [ "${INIT_MODULE_DEFAULTS[$m]}" = 1 ] && MENU_SELECTED+=("$m"); done; fi; }
menu_resolve_selection() { local before=("$@"); REQUESTED_MODULES=("$@"); resolve_modules || return 2; MENU_ADDED_DEPS=(); local m; for m in "${RESOLVED_MODULES[@]}"; do menu_has "$m" "${before[@]}" || MENU_ADDED_DEPS+=("$m"); done; REQUESTED_MODULES=("${RESOLVED_MODULES[@]}"); }

menu_print_results_table() { local i st; printf '%-14s %-20s %s\n' "$(i18n_get results.module)" "$(i18n_get results.status)" "$(i18n_get results.details)"; for i in "${!RESULT_MODULES[@]}"; do st="$(ui_status "${RESULT_STATUSES[$i]// /_}")"; printf '%-14s %-20s %s\n' "${RESULT_MODULES[$i]}" "$st" "${RESULT_DETAILS[$i]}"; done; }
menu_status_summary() { local c=0 n=0 f=0 b=0 s; for s in "${RESULT_STATUSES[@]:-}"; do case "$s" in configured) c=$((c+1));; 'needs changes'|needs_changes|planned) n=$((n+1));; failed|'check failed') f=$((f+1));; blocked) b=$((b+1));; esac; done; ui_section "$(i18n_get results.summary)"; ui_key_value "$(i18n_get results.configured)" "$c"; ui_key_value "$(i18n_get results.needs_changes)" "$n"; ui_key_value "$(i18n_get results.failed)" "$f"; ui_key_value "$(i18n_get results.blocked)" "$b"; }
menu_apply_summary() { local a=0 u=0 f=0 b=0 s=0 x; for x in "${RESULT_STATUSES[@]:-}"; do case "$x" in applied) a=$((a+1));; unchanged) u=$((u+1));; failed) f=$((f+1));; blocked) b=$((b+1));; skipped) s=$((s+1));; esac; done; ui_section "$(i18n_get results.summary)"; ui_key_value "$(i18n_get results.applied)" "$a"; ui_key_value "$(i18n_get results.unchanged)" "$u"; ui_key_value "$(i18n_get results.failed)" "$f"; ui_key_value "$(i18n_get results.blocked)" "$b"; ui_key_value "$(i18n_get results.skipped)" "$s"; }
menu_result_status() { local wanted="$1" i; for i in "${!RESULT_MODULES[@]}"; do [ "${RESULT_MODULES[$i]}" = "$wanted" ] || continue; printf '%s\n' "${RESULT_STATUSES[$i]}"; return 0; done; return 1; }
menu_show_ssh_public_key() { local status key pub; status="$(menu_result_status ssh_key 2>/dev/null || true)"; case "$status" in applied|unchanged) ;; *) return 0;; esac; key="$(target_path "$SSH_KEY_PATH" 2>/dev/null || true)"; [ -n "$key" ] || return 0; pub="${key}.pub"; [ -r "$pub" ] || return 0; ui_section "$(i18n_get apply.github_ssh_key)"; ui_hint "$(i18n_get apply.github_ssh_key_hint)"; printf '\n'; cat "$pub"; printf '\n'; }

menu_show_main() { ui_screen main; ui_section "$(i18n_get main.summary)"; menu_requested_or_default; ui_key_value "$(i18n_get main.target_user)" "${TARGET_USER:-$(i18n_get common.not_selected)}"; ui_key_value "$(i18n_get main.selected_modules)" "${#MENU_SELECTED[@]}"; ui_hint "  ${MENU_SELECTED[*]}"; ui_key_value "$(i18n_get main.configuration)" "$(i18n_get main.defaults)"; ui_key_value "$(i18n_get main.language)" "$(i18n_lang_name "${INIT_EFFECTIVE_LANG}")"; ui_key_value "$(i18n_get main.color_mode)" "$([ -n "${UI_COLOR_TITLE:-}" ] && i18n_get main.enabled || i18n_get main.disabled)"; ui_section "$(i18n_get main.section_actions)"; ui_menu_item 1 "$(i18n_get main.check)"; ui_menu_item 2 "$(i18n_get main.plan)"; ui_menu_item 3 "$(i18n_get main.apply)"; ui_section "$(i18n_get main.section_config)"; ui_menu_item 4 "$(i18n_get main.modules)"; ui_menu_item 5 "$(i18n_get main.config)"; ui_menu_item 6 "$(i18n_get main.effective_config)"; ui_section "$(i18n_get main.section_project)"; ui_menu_item 7 "$(i18n_get main.available_modules)"; ui_menu_item 8 "$(i18n_get main.help)"; ui_menu_item 9 "$(i18n_get main.save)"; ui_menu_item 10 "$(i18n_get main.load)"; ui_menu_item 11 "$(i18n_get main.language)"; ui_menu_item 12 "$(i18n_get main.exit)"; }

menu_select_modules() { local tmp=() choice i m mark; menu_requested_or_default; tmp=("${MENU_SELECTED[@]}"); while :; do ui_screen modules; i=1; for m in "${INIT_REGISTERED_MODULES[@]}"; do mark=' '; menu_has "$m" "${tmp[@]}" && mark=x; ui_menu_item "$i" "[$mark] $m - $(i18n_module_description "$m")"; i=$((i+1)); done; printf '\n'; printf '  a) %s  n) %s  d) %s  c) %s  0) %s\n' "$(i18n_get modules.select_all)" "$(i18n_get modules.select_none)" "$(i18n_get modules.defaults)" "$(i18n_get common.confirm)" "$(i18n_get common.cancel)"; menu_read choice "$(i18n_get common.choice)" || return 0; case "$choice" in 0) menu_flash_info "$(i18n_get modules.cancelled)"; return 0;; a) tmp=("${INIT_REGISTERED_MODULES[@]}");; n) tmp=();; d) tmp=(); for m in "${INIT_REGISTERED_MODULES[@]}"; do [ "${INIT_MODULE_DEFAULTS[$m]}" = 1 ] && tmp+=("$m"); done;; c) menu_resolve_selection "${tmp[@]}" || { menu_pause; return 2; }; [ "${#MENU_ADDED_DEPS[@]}" -gt 0 ] && menu_flash_info "$(i18n_get modules.deps_added) ${MENU_ADDED_DEPS[*]}"; return 0;; ''|*[!0-9]*) menu_invalid;; *) if [ "$choice" -ge 1 ] && [ "$choice" -le "${#INIT_REGISTERED_MODULES[@]}" ]; then m="${INIT_REGISTERED_MODULES[$((choice-1))]}"; if menu_has "$m" "${tmp[@]}"; then local nt=() x; for x in "${tmp[@]}"; do [ "$x" = "$m" ] || nt+=("$x"); done; tmp=("${nt[@]}"); else tmp+=("$m"); fi; else menu_invalid; fi;; esac; done; }
menu_prompt_value() { local var="$1" label="$2" cur val; cur="${!var:-}"; printf '%s current: %s\n' "$label" "${cur:-<$(i18n_get common.empty)>}"; menu_read val "$(i18n_get config.new_value)" || return 1; [ -z "$val" ] && return 0; [ "$val" = '*' ] && printf -v "$var" '' || printf -v "$var" '%s' "$val"; }
menu_toggle() { local var="$1"; [ "${!var:-0}" = 1 ] && printf -v "$var" 0 || printf -v "$var" 1; }
menu_select_target_user() { local ans; printf '%s\n' "$(i18n_get config.target_user_prompt)"; menu_read ans "$(i18n_get config.user)" || return 1; [ -z "$ans" ] && return 0; if [ "$ans" = root ]; then menu_confirm "$(i18n_get config.root_confirm)" || { printf '%s\n' "$(i18n_get config.root_not_selected)"; return 0; }; fi; TARGET_USER="$ans"; }
menu_current_uid() { printf '%s\n' "${EUID:-$(id -u)}"; }
menu_manage_ports() { local c p idx n new=(); while :; do ui_screen ports; idx=1; for p in "${ALLOW_PORTS[@]}"; do ui_menu_item "$idx" "$p"; idx=$((idx+1)); done; printf '\n  a) %s  r) %s  c) %s  0) %s\n' "$(i18n_get ports.add)" "$(i18n_get ports.remove)" "$(i18n_get ports.clear)" "$(i18n_get common.back)"; menu_read c "$(i18n_get common.choice)" || return 0; case "$c" in 0) return 0;; a) menu_read p "$(i18n_get ports.prompt)" || return 0; if validate_port_rule "$p" && ! menu_has "$p" "${ALLOW_PORTS[@]}"; then ALLOW_PORTS+=("$p"); else menu_flash_error "$(i18n_get ports.invalid)"; fi;; r) menu_read n "$(i18n_get ports.remove_number)" || return 0; if [[ "$n" =~ ^[0-9]+$ ]] && [ "$n" -ge 1 ] && [ "$n" -le "${#ALLOW_PORTS[@]}" ]; then new=(); idx=1; for p in "${ALLOW_PORTS[@]}"; do [ "$idx" -eq "$n" ] || new+=("$p"); idx=$((idx+1)); done; ALLOW_PORTS=("${new[@]}"); else menu_flash_error "$(i18n_get ports.invalid_number)"; fi;; c) ALLOW_PORTS=();; *) menu_invalid;; esac; done; }
menu_edit_config() { local c; while :; do ui_screen config; ui_menu_item 1 "$(i18n_get main.target_user)" "${TARGET_USER:-$(i18n_get common.not_selected)}"; ui_menu_item 2 "$(i18n_get config.git_name)" "$GIT_NAME"; ui_menu_item 3 "$(i18n_get config.git_email)" "$GIT_EMAIL"; ui_menu_item 4 "$(i18n_get config.ssh_key_path)" "$SSH_KEY_PATH"; ui_menu_item 5 "$(i18n_get config.ssh_key_comment)" "$SSH_KEY_COMMENT"; ui_menu_item 6 "$(i18n_get config.allow_http)" "$(i18n_bool "$ALLOW_HTTP")"; ui_menu_item 7 "$(i18n_get config.allow_https)" "$(i18n_bool "$ALLOW_HTTPS")"; ui_menu_item 8 "$(i18n_get config.allow_port)" "${ALLOW_PORTS[*]:-}"; ui_menu_item 9 "$(i18n_get config.upgrade)" "$(i18n_bool "$UPGRADE")"; ui_menu_item 10 "$(i18n_get config.assume_yes)" "$(i18n_bool "$ASSUME_YES")"; ui_menu_item 11 "$(i18n_get config.repair_permissions)" "$(i18n_bool "$REPAIR_PERMISSIONS")"; ui_menu_item 12 "$(i18n_get config.force_apply)" "$(i18n_bool "$FORCE_APPLY")"; ui_menu_item 0 "$(i18n_get common.back)"; menu_read c "$(i18n_get common.choice)" || return 0; case "$c" in 0) return 0;; 1) menu_select_target_user;; 2) menu_prompt_value GIT_NAME "$(i18n_get config.git_name)";; 3) menu_prompt_value GIT_EMAIL "$(i18n_get config.git_email)";; 4) menu_prompt_value SSH_KEY_PATH "$(i18n_get config.ssh_key_path)";; 5) menu_prompt_value SSH_KEY_COMMENT "$(i18n_get config.ssh_key_comment)";; 6) menu_toggle ALLOW_HTTP;; 7) menu_toggle ALLOW_HTTPS;; 8) menu_manage_ports;; 9) menu_toggle UPGRADE;; 10) menu_toggle ASSUME_YES;; 11) menu_toggle REPAIR_PERMISSIONS;; 12) menu_toggle FORCE_APPLY;; *) menu_invalid;; esac; done; }

menu_need_target_for_user_modules() {
  local m needs_user=0
  resolve_modules
  for m in "${RESOLVED_MODULES[@]}"; do
    case "$m" in git|ssh_key) needs_user=1; break;; esac
  done
  [ "$needs_user" = 1 ] || return 0

  if get_target_user >/dev/null 2>&1; then
    TARGET_USER="$(get_target_user)"
    return 0
  fi

  if [ "$(menu_current_uid)" -eq 0 ]; then
    ui_key_value "$(i18n_get main.target_user)" root
    menu_confirm "$(i18n_get config.root_confirm)" || {
      printf '%s\n' "$(i18n_get config.root_not_selected)"
      return 1
    }
    TARGET_USER=root
    return 0
  fi

  printf '%s: %s\n' "$(i18n_get main.target_user)" "$(i18n_get common.not_selected)"
  menu_select_target_user
  get_target_user >/dev/null 2>&1
}

menu_run_check() { ui_screen check; menu_need_target_for_user_modules || { menu_pause; return 0; }; run_check_like check; local rc=$?; menu_status_summary; menu_pause; return "$rc"; }
menu_plan_warnings() { local m; ui_key_value "$(i18n_get main.target_user)" "${TARGET_USER:-$(i18n_get common.not_selected)}"; for m in "${RESOLVED_MODULES[@]:-}"; do case "$m" in firewall) ui_hint "$(i18n_get plan.warning_firewall)";; docker) ui_hint "$(i18n_get plan.warning_docker)";; packages) [ "$UPGRADE" = 1 ] && ui_hint "$(i18n_get plan.warning_packages)";; esac; done; }
menu_run_plan() { ui_screen plan; menu_need_target_for_user_modules || { menu_pause; return 0; }; resolve_modules; menu_plan_warnings; run_check_like plan; local rc=$? c; printf '\n'; ui_menu_item 1 "$(i18n_get plan.apply)"; ui_menu_item 2 "$(i18n_get plan.change_modules)"; ui_menu_item 3 "$(i18n_get plan.change_config)"; ui_menu_item 4 "$(i18n_get common.back)"; menu_read c "$(i18n_get common.choice)" || return "$rc"; case "$c" in 1) menu_run_apply;; 2) menu_select_modules;; 3) menu_edit_config;; esac; return "$rc"; }
menu_run_apply() { ui_screen apply; menu_need_target_for_user_modules || { menu_pause; return 0; }; resolve_modules; ui_key_value "$(i18n_get apply.selected_modules)" "${RESOLVED_MODULES[*]}"; menu_plan_warnings; run_check_like plan || true; [ "$UPGRADE" = 1 ] && ui_hint "$(i18n_get plan.warning_packages)"; [ "$REPAIR_PERMISSIONS" = 1 ] && ui_hint "$(i18n_get apply.repair_warning)"; menu_confirm "$(i18n_get apply.confirm)" || { printf '%s\n' "$(i18n_get apply.cancelled)"; menu_pause; return 0; }; run_apply; local rc=$?; ui_separator; menu_apply_summary; menu_show_ssh_public_key; menu_pause; return "$rc"; }
menu_save_config() { ui_screen save; local path tmp p mods; menu_read path "$(i18n_get save.path)" || return 0; [ -n "$path" ] || path='./server.conf'; if [ -e "$path" ]; then menu_confirm "$(i18n_get save.exists)" || { menu_flash_info "$(i18n_get save.not_overwritten)"; return 0; }; fi; for p in "$TARGET_USER" "$GIT_NAME" "$GIT_EMAIL" "$SSH_KEY_PATH" "$SSH_KEY_COMMENT"; do [[ "$p" == *$'\n'* ]] && { printf '%s\n' "$(i18n_get save.no_newlines)"; menu_pause; return 2; }; done; tmp="$(mktemp "${TMPDIR:-/tmp}/init.config.XXXXXX")"; mods="$(menu_join , "${REQUESTED_MODULES[@]}")"; { printf 'language=%s\n' "$INIT_LANG_MODE"; printf 'target_user=%s\n' "$TARGET_USER"; printf 'git_name=%s\n' "$GIT_NAME"; printf 'git_email=%s\n' "$GIT_EMAIL"; printf 'ssh_key_path=%s\n' "$SSH_KEY_PATH"; printf 'ssh_key_comment=%s\n' "$SSH_KEY_COMMENT"; printf 'upgrade=%s\nassume_yes=%s\nallow_http=%s\nallow_https=%s\nrepair_permissions=%s\nforce=%s\n' "$UPGRADE" "$ASSUME_YES" "$ALLOW_HTTP" "$ALLOW_HTTPS" "$REPAIR_PERMISSIONS" "$FORCE_APPLY"; for p in "${ALLOW_PORTS[@]}"; do printf 'allow_port=%s\n' "$p"; done; printf 'modules=%s\n' "$mods"; } > "$tmp" && chmod 600 "$tmp" && mv "$tmp" "$path"; menu_flash_success "$(i18n_get save.saved) $path"; }
menu_snapshot() { MENU_SNAPSHOT=("$TARGET_USER" "$GIT_NAME" "$GIT_EMAIL" "$SSH_KEY_PATH" "$SSH_KEY_COMMENT" "$UPGRADE" "$ASSUME_YES" "$ALLOW_HTTP" "$ALLOW_HTTPS" "$REPAIR_PERMISSIONS" "$FORCE_APPLY" "${REQUESTED_MODULES[*]}" "${ALLOW_PORTS[*]}" "$INIT_LANG_MODE"); }
menu_restore() { TARGET_USER="${MENU_SNAPSHOT[0]}"; GIT_NAME="${MENU_SNAPSHOT[1]}"; GIT_EMAIL="${MENU_SNAPSHOT[2]}"; SSH_KEY_PATH="${MENU_SNAPSHOT[3]}"; SSH_KEY_COMMENT="${MENU_SNAPSHOT[4]}"; UPGRADE="${MENU_SNAPSHOT[5]}"; ASSUME_YES="${MENU_SNAPSHOT[6]}"; ALLOW_HTTP="${MENU_SNAPSHOT[7]}"; ALLOW_HTTPS="${MENU_SNAPSHOT[8]}"; REPAIR_PERMISSIONS="${MENU_SNAPSHOT[9]}"; FORCE_APPLY="${MENU_SNAPSHOT[10]}"; read -r -a REQUESTED_MODULES <<< "${MENU_SNAPSHOT[11]}"; read -r -a ALLOW_PORTS <<< "${MENU_SNAPSHOT[12]}"; i18n_set_lang "${MENU_SNAPSHOT[13]}"; }
menu_load_config() { ui_screen load; local path; menu_read path "$(i18n_get load.path)" || return 0; [ -n "$path" ] || { menu_flash_warning "$(i18n_get load.no_path)"; return 0; }; menu_snapshot; if parse_config_file "$path"; then menu_flash_success "$(i18n_get load.loaded) $path"; else menu_restore; menu_flash_error "$(i18n_get load.failed)"; fi; }
menu_help() { ui_screen help; printf '%s\n' "$(i18n_get help.text)"; menu_pause; }
menu_language() { local c mark_en mark_ru mark_auto; while :; do ui_screen language; mark_en='[ ]'; mark_ru='[ ]'; mark_auto='[ ]'; case "$INIT_LANG_MODE" in en) mark_en='[x]';; ru) mark_ru='[x]';; auto) mark_auto='[x]';; esac; ui_menu_item 1 "$mark_en $(i18n_get lang.english)"; ui_menu_item 2 "$mark_ru $(i18n_get lang.russian)"; ui_menu_item 3 "$mark_auto $(i18n_get lang.auto)"; ui_menu_item 4 "$(i18n_get common.back)"; menu_read c "$(i18n_get common.choice)" || return 0; case "$c" in 1) i18n_set_lang en; menu_flash_success "$(i18n_get lang.changed)";; 2) i18n_set_lang ru; menu_flash_success "$(i18n_get lang.changed)";; 3) i18n_set_lang auto; menu_flash_success "$(i18n_get lang.changed)";; 4|0) return 0;; *) menu_invalid;; esac; done; }
menu_main() { menu_enter; if get_target_user >/dev/null 2>&1; then TARGET_USER="$(get_target_user)"; fi; local c; while :; do menu_show_main; menu_read c "$(i18n_get common.choice)" || { printf '\nExiting.\n'; menu_leave; return 0; }; case "$c" in 0|12) menu_leave; return 0;; 1) menu_run_check || true;; 2) menu_run_plan || true;; 3) menu_run_apply || true;; 4) menu_select_modules || true;; 5) menu_edit_config || true;; 6) ui_screen effective_config; cmd_config; menu_pause;; 7) ui_screen available_modules; cmd_modules; menu_pause;; 8) menu_help;; 9) menu_save_config;; 10) menu_load_config;; 11) menu_language;; *) menu_invalid;; esac; done; }
